---
abstract: 'Interchange6 Open Source Shop Machine'
author:
  - 'Stefan Hornburg (Racke) <racke@linuxia.de>'
build_requires:
  Test::More: '0'
  Test::Most: '0'
  Test::Warnings: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.98, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: Interchange6
no_index:
  directory:
    - t
    - inc
requires:
  DateTime: '0'
  Moo: '1.004005'
  MooX::HandlesVia: '0'
  MooseX::CoverableModifiers: '0.3'
  namespace::clean: '0'
resources:
  IRC: irc://irc.freenode.net/#interchange
  bugtracker: https://github.com/interchange/Interchange6/issues
  repository: https://github.com/interchange/Interchange6.git
version: '0.061'
